stages:
  - build

swarm:
  script: 
    - "export DOMAIN_NAME=evfapp.dev"
    - "REGISTRY=registry.${DOMAIN_NAME}"
    - "name=${CI_PROJECT_DIR##*builds/}"
    - "appName=${name##*/}"
    - "appUserName=${name%/*}"
    - "branchName=${CI_BUILD_REF_NAME}"
    - "email=$(git log --reverse -n 1 $CI_BUILD_REF --pretty=format:\"%ae\")"
    - "appName=${appName//[^[:alnum:]]/}"
    - "appUserName=${appUserName//[^[:alnum:]]/}"
    - "branchName=${branchName//[^[:alnum:]]/}"
    - "if [ $branchName == \"master\" ]; then export APP_IMAGE_NAME=$appUserName\"-\"$appName; else export APP_IMAGE_NAME=$appUserName\"-\"$branchName\"-\"$appName; fi"
    - "APP_IMAGE_NAME=$(echo $APP_IMAGE_NAME | tr '[:upper:]' '[:lower:]')"
    - "NETWORK_NAME=${APP_IMAGE_NAME}"
    - "npm set registry $NPM_REGISTRY"
    - "echo \"Npm Registry - \"${NPM_REGISTRY}"
    - "echo \"App will be pushed to registry - \"${REGISTRY}"
    - "echo \"The image name in registry - \"$APP_IMAGE_NAME"
    - "npm install --no-optional"
    - "time docker build --build-arg HTTP_PROXY=$http_proxy --build-arg HTTPS_PROXY=$https_proxy -t $REGISTRY/$APP_IMAGE_NAME:latest ."
    - "time docker push $REGISTRY/$APP_IMAGE_NAME:latest"
    - "export HAPROXY=10.73.96.189"
    - sed 's/\$NETWORK_NAME/'"$NETWORK_NAME"'/g' qqq.yml > qqq2.yml
    - "mv -f qqq2.yml qqq.yml"
    - docker stack rm $APP_IMAGE_NAME
    - until [ -z "$(docker network ls --filter name=$APP_IMAGE_NAME_$NETWORK_NAME -q)" ]; do sleep 5; done
    - docker stack deploy -c qqq.yml $APP_IMAGE_NAME
    - echo "10.73.96.181    ${APP_IMAGE_NAME}.${DOMAIN_NAME}" >> /etc/hosts
    - isStarted=$(curl -k --write-out %{http_code} --output curl.out --silent https://${APP_IMAGE_NAME}.${DOMAIN_NAME}/)
    - while [ $isStarted -ne 200 ]; do echo ""; echo -n "Waiting till the URL is up..."; export isStarted=$(curl -k --write-out %{http_code} --output curl.out --silent https://${APP_IMAGE_NAME}.${DOMAIN_NAME}/); echo $isStarted; sleep 10; done
    - echo "Your application URL is accessible @ https://${APP_IMAGE_NAME}.${DOMAIN_NAME}"
  stage: build
  tags:
    - EVF_Paas_Runner_Docker_13_181