version: "3"
services:
  web:
    entrypoint: ${STARTUP_CMD}
    image: ${REGISTRY}/${APP_IMAGE_NAME}:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: "10.73.53.144"
      MONGO_HOST: "10.73.53.144"
      CONFIG: ${CONFIG}
      DATASOURCES: ${DATASOURCES}
      PROVIDERS: ${PROVIDERS}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    deploy:
      restart_policy:
        condition: none
    networks:
      - oecloud_ci_test
networks:
  oecloud_ci_test:
    external: true