# ©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),
#Bangalore, India. All Rights Reserved.
version: "3"
services:
  web:
    entrypoint: ${STARTUP_CMD}
    image: ${REGISTRY}/${APP_IMAGE_NAME}:${APP_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      MONGO_HOST: ${MONGO_HOST}
      DB_NAME: ${DB_NAME}
      CONFIG: ${CONFIG}
      DATASOURCES: ${DATASOURCES}
      PROVIDERS: ${PROVIDERS}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_USERNAME: ${ORACLE_USERNAME}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    deploy:
      restart_policy:
        condition: none
    networks:
      - oecloud_ci_test
networks:
  oecloud_ci_test:
    external: true