version: "3"
services:
  web:
    entrypoint: ${STARTUP_CMD}
    image: ${REGISTRY}/${APP_IMAGE_NAME}:latest
    depends_on:
      - mongo
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: "postgres"
      MONGO_HOST: "mongo"
      CONFIG: ${CONFIG}
      DATASOURCES: ${DATASOURCES}
      PROVIDERS: ${PROVIDERS}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    deploy:
      restart_policy:
        condition: none
  mongo:
    image: ${REGISTRY}/alpine-mongo:latest
    deploy:
      restart_policy:
        condition: none
  postgres:
    image: ${REGISTRY}/alpine-postgres:latest
    deploy:
      restart_policy:
        condition: none