version: "2"
services:
  web:
    entrypoint: tail -f server/config.json
    image: ${REGISTRY}/${APP_IMAGE_NAME}
    depends_on:
      - mongo
      - postgres
    ports:
      - "3000"
    environment:
      - NODE_ENV=env
      - MONGO_HOST=mongo
      - POSTGRES_HOST=postgres
      - DATASOURCES=${DATASOURCES}
      - CONFIG=${CONFIG}
      - PROVIDERS=${PROVIDERS}
  mongo:
    image: ${REGISTRY}/alpine-mongo:latest
  postgres:
    image: ${REGISTRY}/alpine-postgres:latest