# ©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),
#Bangalore, India. All Rights Reserved.

version: "3"
services:
  web:
    image: ${REGISTRY}/${APP_IMAGE_NAME}:latest
    depends_on:
      - mongo
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: "postgres"
      MONGO_HOST: "mongo"
      CONFIG: ${CONFIG}
      DATASOURCES: ${DATASOURCES}
      PROVIDERS: ${PROVIDERS}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      VIRTUAL_HOST: "https://${NODE_ENV}-${APP_IMAGE_NAME}.${DOMAIN_NAME},${NODE_ENV}-${APP_IMAGE_NAME}.${DOMAIN_NAME}"
      SERVICE_PORTS: "3000"
      FORCE_SSL: "yes"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 30s
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s
    extra_hosts:
      - "${APP_IMAGE_NAME}.${DOMAIN_NAME}:10.73.96.137"
    networks:
      - router_network
      - ${NETWORK_NAME}
  postgres:
    image: ${REGISTRY}/alpine-postgres:latest
    networks:
      - ${NETWORK_NAME}
  mongo:
    image: ${REGISTRY}/alpine-mongo:latest
    networks:
      - ${NETWORK_NAME}

networks:
  $NETWORK_NAME:
  router_network:
    external: true